# Generated by Django 5.2.16 on 2026-07-20 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('minutos', models.PositiveIntegerField()),
                ('calorias_estimadas', models.PositiveIntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardio_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('series_logradas', models.PositiveIntegerField()),
                ('repeticiones_logradas', models.PositiveIntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('routine_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='routines.routineexercise')),
            ],
        ),
    ]
