# Generated by Django 5.2.16 on 2026-07-20 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('fuerza', 'Fuerza'), ('cardio', 'Cardio')], max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='routines.routine')),
            ],
            options={
                'unique_together': {('routine', 'dia_semana')},
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_objetivo', models.PositiveIntegerField()),
                ('repeticiones_objetivo', models.PositiveIntegerField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutina_ejercicios', to='routines.machine')),
                ('routine_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='routines.routineday')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
