# Generated by Django 5.2.16 on 2026-07-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='tipo',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('dia', 'Pase Diario')], default='mensual', max_length=10),
        ),
    ]
