# Generated by Django 5.2.16 on 2026-07-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plan_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='precio_mensual',
            field=models.PositiveIntegerField(),
        ),
    ]
