# Generated by Django 5.2.16 on 2026-07-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_plan_precio_mensual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='categoria',
        ),
        migrations.AddField(
            model_name='plan',
            name='descripcion_breve',
            field=models.CharField(default='Descripción pendiente', help_text='Breve resumen del plan para mostrar en el inicio y registro', max_length=150),
        ),
    ]
