# Generated by Django 5.2.16 on 2026-07-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_remove_plan_categoria_plan_descripcion_breve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='descripcion_breve',
            field=models.CharField(help_text='Breve resumen del plan para mostrar en el inicio y registro', max_length=150),
        ),
    ]
