# Generated by Django 5.2.16 on 2026-07-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_alter_plan_descripcion_breve'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='plan',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Define el orden en el que aparecerán los planes (el número menor aparece primero).'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='descripcion_breve',
            field=models.CharField(default='', help_text='Breve resumen del plan para mostrar en el inicio y registro', max_length=150),
        ),
    ]
