# Generated by Django 5.2.16 on 2026-07-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_apellido_materno_customuser_edad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='customuser',
            name='qr_base64',
            field=models.TextField(blank=True),
        ),
    ]
